name: 'PR Title Validation'

on:
  pull_request:
    branches:
     - 'master'
     - 'develop'
     - 'release/*'
    paths_ignore:
     - '/infra'

jobs:
  pr-title-check:
    name: 'PR Title Validation'
    if: github.event_name == 'pull_request'
    runs-on: ubuntu_latest
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v3

      - name: 'Run script'
        run: |
          chmod +x ./scripts/pr-title.bash
          ./scripts/pr-title.bash "${{ github.event.pull_request.title }}" "{{ github.head_ref }}" "{{ github.base_ref }}"